name: Build on archlinux with wlroots-17

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  container:
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
      - name: Run in container
        run: |
          cat /etc/pacman.d/mirrorlist
          pacman-key --init
          pacman --noconfirm --noprogressbar -Syu
      - name: Install dep
        run: |
          pacman -Syu --noconfirm --noprogressbar qt6-base qt6-declarative cmake pkgconfig pixman wlroots wayland-protocols git
          pacman -Syu --noconfirm --noprogressbar clang ninja make
          pacman -Syu --noconfirm --noprogressbar fakeroot meson sudo
      - name: Set up user
        run: |
          useradd -m githubuser
          echo -e "root ALL=(ALL:ALL) ALL\ngithubuser ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers
      - name: Install wlr-protocols form the AUR
        run: |
          su githubuser -c "cd ~ && git clone https://aur.archlinux.org/wlr-protocols-git.git && cd ./wlr-protocols-git && makepkg -si --skippgpcheck --noconfirm"
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Configure CMake
        run: |
          mkdir -p ${{github.workspace}}/build
          cmake -B ${{github.workspace}}/build -G Ninja -DWITH_SUBMODULE_QWLROOTS=ON
      - name: Build
        # Build your program with the given configuration
        run: cmake --build ${{github.workspace}}/build
