name: Build on archlinux

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  container:
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
      - name: Run in container
        run: |
          pacman-key --init
          pacman -Syu --noconfirm
      - name: Install dep
        run: |
          pacman -Syu --noconfirm qt6-base qt6-declarative cmake pkgconfig wlroots pixman wayland-protocols git
          pacman -Syu --noconfirm clang ninja
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Configure CMake
        run: |
          mkdir -p ${{github.workspace}}/build
          cmake -B ${{github.workspace}}/build -G Ninja -DWITH_SUBMODULE_QWLROOTS=ON
      - name: Build
        # Build your program with the given configuration
        run: cmake --build ${{github.workspace}}/build
